baseURL = "https://liudf.com/"
languageCode = "zh-cn"
title = "记录我的工作点滴"
theme = "pixyll"

contentdir = "content"
publishdir = "public"
builddrafts = false
author = "liudf"

[indexes]
  category = "categories"
  tag = "tags"
